// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhLyIoJCHCTnFLaLm7-DiN4Oep5PV_hdY',
    appId: '1:418300501529:web:4e0e10b88edd6a5061d488',
    messagingSenderId: '418300501529',
    projectId: 'smarthire-b1f13',
    authDomain: 'smarthire-b1f13.firebaseapp.com',
    storageBucket: 'smarthire-b1f13.firebasestorage.app',
    measurementId: 'G-70C7JPSYCT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzEJKt7dfERCntSnnXazikwWZ9auIIvfQ',
    appId: '1:459828988167:android:4550c6ef42d0b6b3845da2',
    messagingSenderId: '459828988167',
    projectId: 'smarthire-6ee68',
    storageBucket: 'smarthire-6ee68.firebasestorage.app',
  );

  // static const FirebaseOptions android = FirebaseOptions(
  //   apiKey: 'AIzaSyBiuQBBnZVwVuSGUWl_vjZg2eZgMhiW16o',
  //   appId: '1:418300501529:android:a1e795071717ae1c61d488',
  //   messagingSenderId: '418300501529',
  //   projectId: 'smarthire-b1f13',
  //   storageBucket: 'smarthire-b1f13.firebasestorage.app',
  // );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBd9Aa8kFobwhTVJMOAOO77W2J1YHPcNks',
    appId: '1:418300501529:ios:bcf4288d5977fc4061d488',
    messagingSenderId: '418300501529',
    projectId: 'smarthire-b1f13',
    storageBucket: 'smarthire-b1f13.firebasestorage.app',
    iosBundleId: 'com.example.jobApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBd9Aa8kFobwhTVJMOAOO77W2J1YHPcNks',
    appId: '1:418300501529:ios:bcf4288d5977fc4061d488',
    messagingSenderId: '418300501529',
    projectId: 'smarthire-b1f13',
    storageBucket: 'smarthire-b1f13.firebasestorage.app',
    iosBundleId: 'com.example.jobApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhLyIoJCHCTnFLaLm7-DiN4Oep5PV_hdY',
    appId: '1:418300501529:web:8c0eb6474fc7231061d488',
    messagingSenderId: '418300501529',
    projectId: 'smarthire-b1f13',
    authDomain: 'smarthire-b1f13.firebaseapp.com',
    storageBucket: 'smarthire-b1f13.firebasestorage.app',
    measurementId: 'G-YYK1YE9C2S',
  );
}
